### ISSUE TITLE
Bitcoin charset

### ISSUE THREAD

**Issue by belcloud** [tuupola/base58#1]
Hi

Using the bitcoin charset, it seems to be trimming any preceding 0 byte.
For example:
$bitcoin = new Base58(array("characters"=>Base58::BITCOIN));
$a=$bitcoin->decode('1gbCKFk');
$b=$bitcoin->encode($a);

returns 'gbCKFk'

Is this the expected behaviour?

**Comment by peter279k** [comment]
@tuupola, any idea about this?

**Comment by tuupola** [comment]
Possible fix which should be used here too: https://github.com/tuupola/base62/pull/12

**Comment by tuupola** [comment]
This should be fixed in [0.2.0](https://packagist.org/packages/tuupola/base58#0.2.0).
