### ISSUE TITLE
Usage of GMP

### ISSUE THREAD

**Issue by boppy** [tuupola/base58#10]
Regarding:

> This package has both pure PHP and GMP based encoders. By default encoder and decoder will use GMP functions if the extension is installed. If GMP is not available pure PHP encoder will be used instead.

https://github.com/tuupola/base58/blob/9e9cb3b1a8e1b6a540de4a1b1a6d61193756d09a/src/Base58.php#L48-L51

I think there is an `} else {` missing, resulting in GMP never being used, because it will be set in L51 to its PHP brother.

Am I missing something or should I provide an PR? ;)

**Comment by tuupola** [comment]
You are correct `} else {` is missing. Wonder how I have missed that. PR would be great!

**Comment by boppy** [comment]
✔ merged.
