### ISSUE TITLE
Example Script Doesn't Seem to Work

### ISSUE THREAD

**Issue by alexander-morris** [tuupola/base58#8]
This looks like a great resource but I can't seem to get it to run!

After installing with composer and trying your test script: 

```
<?php 
	require __DIR__ . '/vendor/autoload.php';
	use RuntimeException;
	use Tuupola\Base58;

	$base58check = new Base58([
	    "characters" => Base58::BITCOIN,
	    "check" => true,
	    "version" => 0x00
	]);

	print $base58check->encode("Hello world!"); /* 19wWTEnNTWna86WmtFsTAr5 */

	try {
	    $base58check->decode("19wWTEnNTWna86WmtFsTArX");
	} catch (RuntimeException $exception) {
	    /* Checksum "84fec52c" does not match the expected "84fec512" */
	    print $exception->getMessage();
	}
?>
```

It seems to fail with the following error:

`
Warning: The use statement with non-compound name 'RuntimeException' has no effect in test.php on line 3
19wWTEnNTWna86WmtFsTAr5Checksum "84fec52c" does not match the expected "84fec512"`

**Comment by tuupola** [comment]
The example demonstrates how decoding fails with the wrong checksum. If you look closely the result on encode is `19wWTEnNTWna86WmtFsTAr5` while decode is called with deliberately broken base58 string `19wWTEnNTWna86WmtFsTArX`.

Formatting of output would be bit clearer if adding a newline. Also the `use RuntimeException` can be removed to silence the warning.

```php
require "vendor/autoload.php";

use Tuupola\Base58;

$base58check = new Base58([
    "characters" => Base58::BITCOIN,
    "check" => true,
    "version" => 0x00
]);

print $base58check->encode("Hello world!"); /* 19wWTEnNTWna86WmtFsTAr5 */
print "\n";

try {
    $base58check->decode("19wWTEnNTWna86WmtFsTArX");
} catch (RuntimeException $exception) {
    /* Checksum "84fec52c" does not match the expected "84fec512" */
    print $exception->getMessage();
}
```

Yields

```
19wWTEnNTWna86WmtFsTAr5
Checksum "84fec52c" does not match the expected "84fec512"
```

**Comment by alexander-morris** [comment]
Got it! Thanks for the quick response - really appreciate it :)
